config/routes.rb
Rails.application.routes.draw do
  # default
    devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
    root 'home#index'
    get 'home', to: 'home#index'
    get 'friends', to: 'friends#index'
 
    get 'friends/index'
    get 'friends/addfriend'
    get 'friends/unfriend'






    resources :myfiles, only: [:index, :new, :create, :destroy]
    get 'myfiles/delete'
    get 'myfiles/edit'
    

  resources :messages, only: [:create, :new, :inbox, :sent]
  get 'messages/index'
  get 'messages/inbox', to: 'messages#inbox'
  get 'messages/sent', to: 'messages#sent'
  get 'messages/show', to: 'messages#show'
  get 'friends/block'
  get 'friends/unblock'
  resources :messages do
    collection do
      get 'getmess'
    end
  end








end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user_sender, :foreign_key => :sender_id, class_name: 'User'
  belongs_to :user_receiver, :foreign_key => :receiver_id, class_name: 'User'

  validates :sender_id, presence: true
  validates :receiver_id, presence: true
  validates :subject, presence: true
  validates :body, presence: true
  
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
before_action :authenticate_user!
  def index
  end

  def show
    @message = Message.find(params[:id])
    #puts @message.read.inspect
    #puts @message.receiver_id.inspect
    if @message.read == false && @message.receiver_id == current_user.id
      @message.update(read: true, readed_at: Time.zone.now)
      NotifierMailer.read_message(@message).deliver
    end
  end

  def getmess
    id = params[:id]
    @message = Message.find(id.to_i)
    #puts @message.inspect
    respond_to do |format|
    format.html
    format.json {render json: @message}
  end
  end

  def new
    # @friends = User.where.not(id: current_user.id)
    @users = User.where.not(id: current_user.id)

    @temp = Tablefriend.where(id_acc: current_user.id)
    friendArr = []
    @temp.each do |u|
      friendArr.push(u.id_friend)
    end

    @temp = Tablefriend.where(id_friend: current_user.id)
    @temp.each do |u|
      friendArr.push(u.id_acc)
    end

    @friends = User.where('id in (?)', friendArr)
    @message = Message.new
  end

  def create
    # @message = Message.new(message_params)
    # @message.user_sender = current_user
    # if @message.save
    #   flash[:notice] = "Message was successfully sent"
    #   NotifierMailer.new_message(@message).deliver
    #   redirect_to messages_sent_path
    # else render 'new'
    # end
    params[:message][:receiver_id].each do |id|
      if !id.empty?
        @message = Message.new
        @message.sender_id = current_user.id
        @message.subject = params[:message][:subject]
        @message.body = params[:message][:body]
        @message.receiver_id = id
        if @message.save
          flash[:notice] = "Message was successfully sent"
          NotifierMailer.new_message(@message).deliver
        else
          render 'new'
        end
      end
    end
    redirect_to messages_sent_path

  end

  def inbox
    # NotifierMailer.welcome(current_user).deliver
    @temp = BlockFriend.where(id_acc: current_user.id)
    b_friendArr = []
    b_friendArr.push(0)
    @temp.each do |u|
      b_friendArr.push(u.id_friend)
    end

    @messages = Message.where('sender_id not in (?) and receiver_id = (?)',b_friendArr,current_user.id).all.order('created_at DESC')
    @count_unread_inbox = Message.where(receiver_id: current_user.id, read: false).where('sender_id not in (?)',b_friendArr).count
    @count_unread_sent = Message.where(sender_id: current_user.id, read: false).count
    @active = :inbox
  end

  def sent
    @messages = Message.where(sender_id: current_user.id).all.order('created_at DESC')
    @count_unread_inbox = Message.where(receiver_id: current_user.id, read: false).count
    @count_unread_sent = Message.where(sender_id: current_user.id, read: false).count
    @active = :sent
  end

  def trash
    @active = :trash
  end

  def important
    @active = :important
  end

  def drafts
    @active = :drafts
  end

  private
    # def message_params
    #   params.require(:message).permit(:receiver_ids [], :body, :subject)
    # end
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/messages/_left-side.html.erb
<aside class="sm-side" id="left-side">
<%= link_to  "New Message", new_message_path, class: "btn btn-compose" %>
  <ul class="inbox-nav inbox-divider">
    <li class="<%= active_page(:inbox) %>">
       <%= link_to  messages_inbox_path do %>
        <i class="fa fa-inbox"></i>
        Inbox
        <span class="label label-danger pull-right"><%= @count_unread_inbox%></span>
      <% end %>
    </li>
    <li class="<%= active_page(:sent) %>">
      <%= link_to  messages_sent_path do %>
        <i class="fa fa-rocket"></i>
        Sent Mail
        <span class="label label-primary pull-right"><%= @count_unread_sent%></span>
      <% end %>
    </li>
    <li class="<%= active_page(:important) %>">
      <a href="#">
        <i class="fa fa-bookmark-o"></i>
        Important</a>
    </li>
    <li class="<%= active_page(:drafts) %>">
      <a href="#">
        <i class=" fa fa-external-link"></i>
        Drafts</a>
    </li>
    <li class="<%= active_page(:trash) %>">
      <a href="#">
        <i class=" fa fa-trash-o"></i>
        Trash</a>
    </li>
  </ul>
</aside>

app/views/messages/inbox.html.erb
<div class="container">
  <div class="mail-box">
    <%= render partial: 'left-side' %>
    <aside class="lg-side">
      <div class="inbox-head">
        <h3>Inbox</h3>
        <form action="#" class="pull-right position">
          <div class="input-append">
            <input type="text" class="sr-input" placeholder="Search Mail">
            <button class="btn sr-btn" type="button">
              <i class="fa fa-search"></i>
            </button>
          </div>
        </form>
      </div>
      <div class="inbox-body">
        <table class="table table-inbox table-hover">
          <tbody>
            <tr>
              <th>From</th>
              <th>Subject</th>
              <th>Received At</th>
              <th>Action</th>
            </tr>
            <% @messages.each do |m| %>
            <% if m.read %>
            <tr class="" data-id="<%= m.id %>">
            <% else %>
              <tr class="unread" data-id="<%= m.id %>">
                <% end %>
                <td class="view-message"><%= m.user_sender.fullname %></td>
                <td class="view-message"><%= m.subject%></td>
                <td class="view-message"><%=time_ago_in_words( m.created_at)%></td>
                <% if m.read %>
                <td><%= link_to "Read", m , data: { confirm: 'You readed this messages, you want to read agian?'} %></td>
                <% else %>
                <td><%= link_to "Read", m %></td>
                <% end %>
              </tr>
              <% end %>
            </tbody>
          </table>
      </div>
    </aside>
  </div>
</div>

app/views/messages/index.html.erb
<h1>Messages#index</h1>
<p>Find me in app/views/messages/index.html.erb</p>

app/views/messages/new.html.erb
<div class="container">
  <div class="mail-box">
    <%= render partial: 'left-side' %>
    <aside class="lg-side">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <h4 class="modal-title">Compose</h4>
          </div>
          <div class="modal-body">

            <%= form_for(@message, :html => {class: "form-horizontal", role: "form"}) do |f|%>
            <% if @message.errors.any? %>
            <div id="errors">
              <h2>
                <%= pluralize(@message.errors.count, "error") %>
                prevented this message from saving
              </h2>
              <ul>
                <% @message.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
                <% end %>
              </ul>
            </div>
            <% end %>
            <div class="form-group">
              <label class="col-lg-2 control-label">To</label>
              <div class="col-lg-10">
                <%= collection_select(:message, :receiver_id, @friends, :id, :fullname, {}, {:multiple => true, include_blank: false, class: "ui fluid  selection dropdown", id: "select-receiver_id",:prompt => 'Please select the friends'}) %>
              </div>
            </div>

            <div class="form-group">
              <label class="col-lg-2 control-label">Subject</label>
              <div class="col-lg-10">
                <%= f.text_field :subject, class: "form-control input-lg", placeholder: "", required: true %>
              </div>

            </div>

            <div class="form-group">
              <label class="col-lg-2 control-label">Message</label>
              <div class="col-lg-10">
                <%= f.text_area :body, class: "form-control", placeholder: "", required: true, rows: 10%>
              </div>
            </div>

            <div class="form-group">
              <div class="center" style="text-align:center;">
                <%= f.submit "Send", class: "btn btn-send" %>
              </div>
            </div>
            <% end%>

          </div>
        </div>
        <!-- /.modal-content -->
      </div>
    </aside>
  </div>
</div>

app/views/messages/sent.html.erb
<div class="container">
  <div class="mail-box">
    <%= render partial: 'left-side' %>
    <aside class="lg-side">
      <div class="inbox-head">
        <h3>Sent Mail</h3>
        <form action="#" class="pull-right position">
          <div class="input-append">
            <input type="text" class="sr-input" placeholder="Search Mail">
            <button class="btn sr-btn" type="button">
              <i class="fa fa-search"></i>
            </button>
          </div>
        </form>
      </div>
      <div class="inbox-body">
        <table class="table table-inbox table-hover">
          <tbody>
            <tr>
              <th>To</th>
              <th>Subject</th>
              <th>Readed At</th>
              <th>Action</th>
            </tr>
            <% @messages.each do |m| %>
            <% if m.read %>
            <tr class="" data-id="<%= m.id %>" data-link="<%= m %>">
            <% else %>
              <tr class="unread" data-id="<%= m.id %>">
                <% end %>
                <td class="view-message"><%= m.user_receiver.fullname %></td>
                <td class="view-message"><%= m.subject%></td>
                <td class="view-message"><% if m.read %><%=time_ago_in_words(m.readed_at)%><%else%>Not yet<% end %></td>
                <td><%= link_to "Read", m %></td>
              </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </aside>
    </div>
  </div>

app/views/messages/show.html.erb
<div class="container">
  <div class="mail-box">
    <%= render partial: 'left-side' %>
    <aside class="lg-side">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <h4 class="modal-title">Detail Message</h4>
          </div>
          <div class="modal-body">
            <form role="form" class="form-horizontal">
              <% if @message %>
              <div class="form-group">
                <label class="col-lg-2 control-label">From</label>
                <div class="col-lg-10">
                  <label class="control-label" id="lbfrom">
                    <a href="#"><%= @message.user_sender.fullname + " - " + @message.user_sender.email %></a>
                  </label>
                </div>
              </div>

              <div class="form-group">
                <label class="col-lg-2 control-label">To</label>
                <div class="col-lg-10">
                  <label class="control-label" id="lbto">
                    <a href="#"><%= @message.user_receiver.fullname + " - " + @message.user_receiver.email %></a>
                  </label>
                </div>
              </div>

              <div class="form-group">
                <label class="col-lg-2 control-label">Created at</label>
                <div class="col-lg-10">
                  <label class="control-label" id="lbsubject"><%=time_ago_in_words(@message.created_at)%></label>
                </div>
              </div>

              <div class="form-group">
                <label class="col-lg-2 control-label">Subject</label>
                <div class="col-lg-10">
                  <label class="control-label" id="lbsubject"><%= @message.subject %></label>
                </div>
              </div>

              <div class="form-group">
                <label class="col-lg-2 control-label">Message</label>
                <div class="col-lg-10">
                  <textarea rows="10" cols="30" class="form-control" id="txtMess" name="" id="txtcontent"><%= @message.body %></textarea>
                </div>
              </div>
              <% end %>
            </form>
          </div>
        </div>
      </div>
    </aside>
  </div>
</div>