config/routes.rb
Rails.application.routes.draw do
  # default
    devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
    root 'home#index'
    get 'home', to: 'home#index'
    get 'friends', to: 'friends#index'
 
    get 'friends/index'
    get 'friends/addfriend'
    get 'friends/unfriend'






    resources :myfiles, only: [:index, :new, :create, :destroy]
    get 'myfiles/delete'
    get 'myfiles/edit'
    

  resources :messages, only: [:create, :new, :inbox, :sent]
  get 'messages/index'
  get 'messages/inbox', to: 'messages#inbox'
  get 'messages/sent', to: 'messages#sent'
  get 'messages/show', to: 'messages#show'
  get 'friends/block'
  get 'friends/unblock'
  resources :messages do
    collection do
      get 'getmess'
    end
  end








end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  before_action :authenticate_user!
  def index
    @users = User.where.not(id: current_user.id)

    @temp = Tablefriend.where(id_acc: current_user.id)
    friendArr = []
    @temp.each do |u|
      friendArr.push(u.id_friend)
    end

    @temp = Tablefriend.where(id_friend: current_user.id)
    @temp.each do |u|
      friendArr.push(u.id_acc)
    end

    @Tablefriends = User.where('id in (?)', friendArr)
    @block_friends = BlockFriend.where(id_acc: current_user.id)
  end

  def addfriend
    @friend = Tablefriend.new(id_acc: current_user.id, id_friend: params[:id_friend])
    if @friend.save
      flash[:notice] = "Add friend is successed"
    end
    redirect_to '/friends/index'
  end

  def unfriend
    Tablefriend.where(id_acc: current_user.id ,id_friend: params[:id_friend]).destroy_all
    Tablefriend.where(id_acc: params[:id_friend], id_friend: current_user.id).destroy_all
    BlockFriend.where(id_acc: current_user.id ,id_friend: params[:id_friend]).destroy_all
    flash[:notice] = "Unfriend is successed"
    redirect_to '/friends/index'
  end

  def block
    @block_friend = BlockFriend.new(id_acc: current_user.id, id_friend: params[:id_friend])
    if @block_friend.save
      flash[:notice] = "Block friend is successed"
    end
    redirect_to '/friends/index'
  end

  def unblock
    BlockFriend.where(id_acc: current_user.id ,id_friend: params[:id_friend]).destroy_all
    flash[:notice] = "Unblock is successed"
    redirect_to '/friends/index'
  end


end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/views/friends/index.html.erb
<div class="container">
  <h1>Friends</h1>
  <table class="table">
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Status</th>
    </tr>
    <% @users.each do |user| %>
    <tr>
      <% tag = true %>
      <td><%= user.fullname %></td>
      <td><%= user.email %></td>
      <td>
      <% @Tablefriends.each do |tablefriend| %>

        <%- if (user.id == tablefriend.id) %>
            <%= link_to "Unfriend", friends_unfriend_path(:id_friend => user.id), class: "btn btn-danger" %>
            <% tag = false %>


            <% flag = true%>
            <% @block_friends.each do |b_friend| %>
              <% if (tablefriend.id == b_friend.id_friend) %>
                <%= link_to "UnBlock", friends_unblock_path(:id_friend => user.id), class: "btn btn-success" %>
                <% flag = false%>
                <% break %>
              <% end %>
            <% end %>
            <% if flag %>
              <%= link_to "Block", friends_block_path(:id_friend => user.id), class: "btn btn-warning" %>
            <%end %>
            <% break %>
        <% end -%>

      <% end %>

      <% if tag %>
        <%= link_to "Add Friend", friends_addfriend_path(:id_friend => user.id), class: "btn btn-primary" %>
      <%end %>
      </td>
    </tr>
    <% end %>
  </table>
</div>