config/routes.rb
Rails.application.routes.draw do
  # default
    devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
    root 'home#index'
    get 'home', to: 'home#index'
    get 'friends', to: 'friends#index'
 
    get 'friends/index'
    get 'friends/addfriend'
    get 'friends/unfriend'






    resources :myfiles, only: [:index, :new, :create, :destroy]
    get 'myfiles/delete'
    get 'myfiles/edit'
    

  resources :messages, only: [:create, :new, :inbox, :sent]
  get 'messages/index'
  get 'messages/inbox', to: 'messages#inbox'
  get 'messages/sent', to: 'messages#sent'
  get 'messages/show', to: 'messages#show'
  get 'friends/block'
  get 'friends/unblock'
  resources :messages do
    collection do
      get 'getmess'
    end
  end








end

app/models/myfile.rb
class Myfile < ApplicationRecord
    mount_uploader :attachment, AttachmentUploader # Tells rails to use this uploader for this model.
   #validates :name, presence: true # Make sure the owner's name is present.

   belongs_to :user_sender, :foreign_key => :user_id, class_name: 'User'

# validate :attachment_size_validation, :if => "attachment?"  

# def attachment_size_validation
#     puts attachment.size
#     errors[:attachment] << "should be less than 2MB" if attachment.size > 2.megabytes
# end
end

app/controllers/myfiles_controller.rb
class MyfilesController < ApplicationController
  #before_action :authenticate_user!
  before_action :authenticate_user!, except: [:index]

  def index
    @myfiles = Myfile.all.order('created_at DESC')
    @count_files = @myfiles.count
  end

  def new
    @myfile = Myfile.new
 end
 
 def create

 
      params[:item_files]['file'].each do |f|
        @myfile = Myfile.new
        @myfile.attachment = f
        # take array string by split
        str = @myfile.attachment.to_s.split('/')
        @myfile.name = str[str.count-1]
        @myfile.size = @myfile.attachment.size
        @myfile.user_id = current_user.id
        @myfile.save
      end

    redirect_to myfiles_path, notice: "The files has been uploaded."
    # @myfile = Myfile.new(myfile_params)
    # if @myfile.save
    #    redirect_to myfiles_path, notice: "The file #{@myfile.name} has been uploaded."
    # else
    #    render "new"
    # end   
 end
 
 def destroy
    @myfile = Myfile.find(params[:id])
    @myfile.destroy
    redirect_to myfiles_path, notice:  "The file #{@myfile.name} has been deleted."
 end
 
  
 def edit
  redirect_to myfiles_path
  # flash[:notice] = "Unfriend is successed"
  # redirect_to '/friends/index'
  end

 def delete
  @myfile = Myfile.find(params[:id_file])
  @myfile.destroy
  redirect_to myfiles_path, notice:  "The file #{@myfile.name} has been deleted."
  # flash[:notice] = "Unfriend is successed"
  # redirect_to '/friends/index'
end

 private
    def myfile_params
    params.require(:myfile).permit(:name, :attachment)
 end

end

app/views/myfiles/create.html.erb
<h1>Myfiles#create</h1>
<p>Find me in app/views/myfiles/create.html.erb</p>

app/views/myfiles/destroy.html.erb
<h1>Myfiles#destroy</h1>
<p>Find me in app/views/myfiles/destroy.html.erb</p>

app/views/myfiles/index.html.erb
<div class="container">
<% if !flash[:notice].blank? %>
   <div class = "alert alert-info">
      <%= flash[:notice] %>
   </div>
<% end %>

<br />

<%= link_to "Upload File", new_myfile_path, class: "btn btn-primary" %>
<br />
<br />
<span class="">Total files: <%= @count_files%></span>
<table class = "table table-bordered table-striped">
   <thead>.
      <tr>
		    <th>Name</th>
            <th>Owner</th>
            <th>Last Modified</th>
            <th>File Size</th>
            <th></th>
      </tr>
   </thead>
   
   <tbody>
      <% @myfiles.each do |myfile| %>
         <tr>
            <td><span class="fa fa-file">   <span/><%= link_to myfile.name, myfile.attachment_url %></td>
            <td><%#= myfile.user_sender.fullname%></td>
		    <td><%=time_ago_in_words(myfile.updated_at)%></td>
            <td><%= number_to_human_size(myfile.size)%></td>
            <td><%= link_to "Edit", myfiles_edit_path(:id_file => myfile.id), class: "btn btn-primary" %> | 
            <%= link_to "Destroy", myfile, method: :delete,  class: "btn btn-danger", data: { confirm: "Are you sure?" } %>
            <!-- 
            <%= button_to "Delete",  myfile, method: :delete, class: "btn btn-danger", confirm: "Are you sure that you wish to delete #{myfile.name}?" %>
            -->
         </tr>
      <% end %>
   </tbody>
</table>
</div>

app/views/myfiles/new.html.erb
<% if !@myfile.errors.empty? %>
   <div class = "alert alert-error">
      <ul>
         <% @myfile.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
         <% end %>
      </ul>
   </div>
<% end %>

<div class = "well">
   <%= form_for @myfile, html: { multipart: true } do |f| %>
    <%= f.file_field :attachment, multiple: true, name: "item_files[file][]"%>   
      <%#= f.file_field :attachment %>
      <%= f.submit "Save", class: "btn btn-primary" %>
   <% end %>
</div>